export const defaultData = {
    address: "One Apple Park Way",
    beta:1.297088,
    ceo:"Mr. Timothy D. Cook",
    changes:1.16,
    cik:"0000320193",
    city:"Cupertino",
    country:"US",
    currency:"USD",
    cusip:"037833100",
    dcf:150.082,
    dcfDiff:4.15176,
    defaultImage:false,
    description:"Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services. In addition, the company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; AirPods Max, an over-ear wireless headphone; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, HomePod, and iPod touch. Further, it provides AppleCare support services; cloud services store services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. Additionally, the company offers various services, such as Apple Arcade, a game subscription service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was incorporated in 1977 and is headquartered in Cupertino, California.",
    exchange:"NASDAQ Global Select",
    exchangeShortName:"NASDAQ",
    fullTimeEmployees:"164000",
    industry:"Consumer Electronics",
    ipoDate:"1980-12-12",
    isActivelyTrading:true,
    isAdr:false,
    isEtf:false,
    isFund:false,
    isin:"US0378331005",
    lastDiv:0.92,
    mktCap:2632605903729,
    phone:"408 996 1010",
    range:"124.17-176.15",
    sector:"Technology",
    state:"CA",
    volAvg:64579973,
    website:"https://www.apple.com",
    zip:"95014",
}